name: Server

on:
  push:
    branches:
      - "**"

env:
  CI: "true"
  DEBUG: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test